import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import SocialRail from "@/components/layout/SocialRail";
import EmailRail from "@/components/layout/EmailRail";
import JsonLd from "@/components/seo/JsonLd";
import { siteUrl, siteDescription } from "@/data/profile";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

const title = "Taiwo Joseph | Frontend Engineer";
const titleDefault =
  "Taiwo Joseph | Frontend Engineer for FinTech, Marketplaces & Logistics";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    template: `%s | ${title}`,
    default: titleDefault,
  },
  description: siteDescription,
  applicationName: "Taiwo Joseph Portfolio",
  authors: [{ name: "Taiwo Joseph", url: siteUrl }],
  generator: "Next.js",
  category: "technology",
  keywords: [
    "Taiwo Joseph",
    "frontend engineer",
    "frontend lead",
    "React engineer",
    "Next.js developer",
    "Vue developer",
    "TypeScript developer",
    "FinTech frontend engineer",
    "marketplace developer",
    "web performance",
    "Lagos frontend engineer",
    "JTK",
  ],
  creator: "Taiwo Joseph",
  publisher: "Taiwo Joseph",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: titleDefault,
    description: siteDescription,
    url: siteUrl,
    siteName: "Taiwo Joseph Portfolio",
    locale: "en_US",
    type: "website",
    // OG image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    site: "@KelvinJoseph10",
    title: titleDefault,
    description: siteDescription,
    creator: "@KelvinJoseph10",
    // Twitter image is generated by app/twitter-image.tsx (file convention).
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0B1A32" },
  ],
  colorScheme: "light dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans bg-white dark:bg-secondary`}
      >
        <JsonLd />
        <Providers>
          <div className="relative mx-auto min-h-dvh max-w-[1600px] bg-white dark:bg-secondary">
            <Navbar />
            {children}
            <Footer />
            <SocialRail />
            <EmailRail />
          </div>
        </Providers>
      </body>
    </html>
  );
}
