import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import Navbar from "@/components/Navbar";
import Socials from "@/components/Socials";
import Link from "next/link";
import EmailContact from "@/components/EmailContact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Taiwo Joseph",
    default: "Taiwo Joseph",
  },
  description: "Generated by create next app",
  applicationName: "Taiwo Joseph Portfolio",
  authors: [{ name: "Taiwo Joseph" }],
  generator: "Next.js",
  keywords: ["taiwo joseph", "web development", "programmer"],
  creator: "Taiwo Joseph",
  publisher: "Taiwo Joseph",
  openGraph: {
    title: "Taiwo Joseph",
    description: "",
    url: "",
    siteName: "Taiwo Joseph Portfolio",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "",
        secureUrl: "",
        width: "1200",
        height: "630",
        alt: "Preview Image for Taiwo Joseph",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "",
    title: "Taiwo Joseph",
    description: "",
    creator: "",
    images: {
      url: "",
      alt: "Preview Image for Taiwo Joseph",
    },
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-secondary`}>
        <Providers>
          <div className="min-h-dvh max-w-[1600px] mx-auto bg-white dark:bg-secondary">
            <Navbar />
            {children}
            <Socials />
            <EmailContact />
          </div>
        </Providers>
      </body>
    </html>
  );
}
